paths:
  raw: data/raw/insurance_claims_complete.csv
  interim: data/interim/insurance_interim.parquet
  processed: data/processed/dataset.parquet
  train: data/splits/train.parquet
  test: data/splits/test.parquet
target: fraud_reported
split:
  test_size: 0.2
  random_state: 42
